2024-04-30 11:19:55,791 ERROR:An unexpected error occurred
Traceback (most recent call last):
  File "C:\Users\EMC\Desktop\resume parsernew\main.py", line 25, in upload_file
    raise HTTPException(status_code=400, detail="Unsupported file type")
TypeError: HTTPException() takes no keyword arguments
2024-04-30 11:20:58,493 ERROR:An unexpected error occurred
Traceback (most recent call last):
  File "C:\Users\EMC\Desktop\resume parsernew\main.py", line 25, in upload_file
    raise HTTPException(status_code=400, detail="Unsupported file type")
TypeError: HTTPException() takes no keyword arguments
